export const appointments = [
  {
    id: 0,
    patientName: "Alice Johnson",
    date: "2023-06-14",
    time: "09:00",
    duration: 60,
    doctorName: "Dr. John Doe",
    department: "Dermatology",
    reason: "Skin rash",
    status: "Confirmed",
    prescriptions: [
      {
        id: 0,
        medication: "Hydrocortisone",
        dosage: "1%",
        frequency: "Twice daily",
        duration: "14 days",
        prescribedBy: "Dr. John Doe",
        dateIssued: "2023-06-14",
        notes: "Apply to affected area",
      },
    ],
  },
  {
    id: 1,
    patientName: "John Doe",
    date: "2023-06-15",
    time: "14:30",
    duration: 30,
    doctorName: "Dr. Jane Smith",
    department: "Cardiology",
    reason: "Annual checkup",
    status: "Scheduled",
    prescriptions: [
      {
        id: 1,
        medication: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        duration: "30 days",
        prescribedBy: "Dr. Jane Smith",
        dateIssued: "2023-06-15",
        notes: "Take with food",
      },
      {
        id: 2,
        medication: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        duration: "90 days",
        prescribedBy: "Dr. Jane Smith",
        dateIssued: "2023-06-15",
        notes: "Take with meals",
      },
    ],
  },
  {
    id: 2,
    patientName: "Jane Smith",
    date: "2023-06-16",
    time: "10:00",
    duration: 45,
    doctorName: "Dr. Michael Johnson",
    department: "Neurology",
    reason: "Follow-up consultation",
    status: "Confirmed",
    prescriptions: [],
  },
];
