export const lables = {
  email: "Email",
  phone: "Phone",
  mobile: "Mobile",
  password: "Password",
  name: "Name",

  facilities: "Facilities",
  appointments: "Appointments",
  subFacilities: "Sub-facilities",
  subFacility: "Sub-facility",
  addSubFacility: "Add sub-facility",
  people: "People",
  person: "Person",
  addPerson: "Add person",
  addDoctor: "Add doctor",
  addMedicalStaff: "Add medical staff",
  addStaff: "Add staff (non-medical)",

  specialization: "Specialization",
  qualification: "Qualification",
  experience: "Experience",

  contactInformation: "Contact information",
  address: "Address",

  licenseInformation: "License information",
  licenseAuthority: "License authority",
  licenseNumber: "License number",
  licenseExpiry: "License expiry",
  licenseImage: "License image",

  fees: "Fees",
  consultingFee: "Consulting fee",
  reportingFee: "Reporting fee",

  associatedFacility: "Associated facility",

  age: "Age",
  weight: "Weight",
  height: "Height",
  temperature: "Temperature",
  bloodPressure: "Blood Pressure",
  pulseRate: "Pulse Rate",
  respiratoryRate: "Respiratory Rate",
  oxygenSaturation: "Oxygen Saturation",
  bloodSugar: "Blood Sugar",
  hemoglobin: "Hemoglobin",
  cholesterol: "Cholesterol",
  triglycerides: "Triglycerides",
  hdl: "HDL",
  ldl: "LDL",
  vldl: "VLDL",
  tsh: "TSH",
  t3: "T3",
  t4: "T4",
  rbc: "RBC",
  wbc: "WBC",
  platelets: "Platelets",
  neutrophils: "Neutrophils",
  lymphocytes: "Lymphocytes",
  monocytes: "Monocytes",
  eosinophils: "Eosinophils",
  basophils: "Basophils",
  prothrombinTime: "Prothrombin Time",
  inr: "INR",
  aptt: "APTT",
  pt: "PT",
  ptt: "PTT",
  fibrinogen: "Fibrinogen",
  dDimer: "D-Dimer",
  troponin: "Troponin",
  ck: "CK",
  ckmb: "CK-MB",
  ldh: "LDH",
  crp: "CRP",
  esr: "ESR",
  hba1c: "HbA1c",
  albumin: "Albumin",
  bilirubin: "Bilirubin",
  alkalinePhosphatase: "Alkaline Phosphatase",
  alt: "ALT",
  ast: "AST",
  ggt: "GGT",
  amylase: "Amylase",
  lipase: "Lipase",
  creatinine: "Creatinine",
  urea: "Urea",
  uricAcid: "Uric Acid",
  sodium: "Sodium",
  potassium: "Potassium",
  chloride: "Chloride",
  calcium: "Calcium",
  magnesium: "Magnesium",
  phosphate: "Phosphate",

  conditionsNotes: "Condition's Notes",
  conditionsRemarks: "Condition's Remarks",

  medications: "Medications",
  searchMedicine: "Search Medicine",
  diagnosisNotes: "Diagnosis's Notes",
};
